version: '3.8'
services:
  db:
    image: mongo:latest
    container_name: PostagemFIAP
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=Admin
      - MONGO_INITDB_ROOT_PASSWORD=Adminpassword

volumes:
  mongo_data:
